sudo: required

language: python

services:
  - docker

before_install:
- docker pull tp33/django
- docker pull mysql:5.7.14
- mkdir db
- docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
- sleep 20
- docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 mysql -uroot -p'$3cureUS' -h db -e "create user 'www'@'%' identified by '$3cureUS'; create database cs4501 character set utf8; grant all on cs4501.* to 'www'@'%';"
- docker rm mysql-cmdline
- docker ps -a

before_script:
- docker-compose up -d
- sleep 50
script:
- docker exec -it models_container bash -c "cd models && python manage.py test"