# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170510_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='item_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_items',
            field=models.TextField(),
        ),
    ]
